### ISSUE TITLE
Trying to understand the communication between the services / containers

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#12]
Edit: Read the Docs again and of course it states that the Frontend/Apps require access to the DB, not only to the API. I still wonder what the 4 parameters do :-)

First: Thank you so much for sharing your work with everyone else! I got everything up and running thanks to your documentation and examples in less than 30 minutes in my Docker environment. So far so good :-)

Next step is to implement it properly in my environment (various VLANs, Traefik Reverse Proxy etc.) to host it as secure as possible.
And I struggle a bit understanding the communication between the CouchDB, Backend and Frontend.

My assumption was that the Frontend and the Android App both exclusively connect to the API of the Backend, so this was what I route through Traefik. When pointing the Frontend or the Mobile App to Traefik, I can create new Users, but I was not able to log in. So communication is working... sort of. But I think I am not understanding the communication correctly.

I assumed it is App --> API/Backend --> CouchDB.
But I suspect it is more like
App --> API/Backend --> CouchDB
    |-----------------------> CouchDB
maybe?

I do not understand the difference between
- COUCHDB_URL
- COUCHDB_INTERNAL_URL

and

- GROCERY_URL
- GROCERY_API_URL

If my 1st assumption is right regarding the communication, I can make no sense out of the 2 DB and 2 API URLs we have to provide in the Backend.

Also I do not understand yet how I can create Users from the Frontend / Backend (which I can also see in the CouchDB Database), but can not login. Unfortunately the Container Logs log nothing when I try to log in. Is there a Debug mode I can enable to see more messages from the services, so I can provide better information here?

As said before: Thank you very much. Got it running in the "lab" pretty quick, but bringing it securely Online is something I struggle a bit at the moment :-)

**Comment by davideshay** [comment]
COUCHDB_URL -- the fully qualified domain name that you can access the couch database from . This would need to be externally accessible if you aren't using a VPN and want to use it outside of the house. This URL is passed from the API server back to the frontend when you login to the app/website. The app then uses this to setup sync between the local pouchDB and CouchDB. The app really relies on this behavior, and the quality of this sync is worth it, IMO.  In my implementation, I use an Ingress in kubernetes to direct from couchdb.mydomain.com to my internal  couchdb implementation running on port 5984. I also use ModSecurity to provide some basic security against typical HTTP attacks. 

COUCHDB_INTERNAL_URL -- this is another hostname to access the same couchDB instance. I use this to enable direct communication from the API server to couchDB without going through an ingress --  this could be a docker service name or I use a kubernetes service name . If not supplied, you can use the same as COUCHDB_URL.

GROCERY_URL -- Really not used for much in the backend other than sending out informative emails, which provides a link to the externally accessible groceries website.

GROCERY_API_URL - Again only used in sending out emails, but those emails include links to API server actions to create an account or reset a password.  Also an "externally" accessible API URL link.

Creating users should be done in the frontend -- when you first start the app, you should be able to create an account with a button on the login page - create account. You should be prompted for a user name and password as well as an email address and full name. The API server takes this info and creates an account for you in the couchDB _users database, and also issues back an access and refresh JWT. The JWT is stored in the users database in couchDB as well, so would not be easy to create an account yourself in couchDB.

If I had to guess, you might be having a problem with the HMAC key setup and/or admin user/password for CouchDB. Couple of things to check:

- Make sure the _users and _replication database is created in couchDB. 
- Make sure you have a valid username and password that has "admin" access to couchDB across all databases. You should be able to test this by going to http://my-couchdb-url:5984/_utils and logging in.
- To help with the above, you might want to put your admin user/password in an "admin.ini" file in the couchDB setup directories.
- You need to have the JWT values setup in the couchDB setup directories. See the sample jwt.ini [here](https://github.com/davideshay/groceries/blob/master/docs/jwt.ini).   The key here is that you need a value in the COUCHDB_HMAC_KEY value that is plaintext, say "haven-copier-defective" and then in jwt.ini, under the jwt_keys key you would need something like "hmac:_default = aGF2ZW4tY29waWVyLWRlZmVjdGl2ZQ==".  

If that fails, I'd have to add some logging in the API server -- have you checked the Javascript console in the frontend to see what happens when you create a user or try to login though?

Can always DM me on reddit for more guidance.

**Comment by kladderadeng** [comment]
Thank you very much for your thorough response. That clears up a lot of questions :-)

You suggest to focus on the Frontend before going to the apps, so this is what I did. I looked over the whole setup, deleted the existing databases and started fresh to see what's going on.

I think the HMAC key setup and admin password should be OK, because I can create Users, the tables get populated with the users + default items and I can see in the Browser debugging session that I get Authentication tokens.
But I do not see any data in the Frontend.

If I understand your explanation correct, creating a User flows Frontend -> Backend/API -> CouchDB. The same for the login. After the login, data flows Frontend <--> CouchDB. If I understand this correctly, I might have a good setup for the first part, but problems communicating between the Frontend and the CouchDB.

My CouchDB + API are available over my Traefik setup.
The CouchDB via https://my.url/db and the API via https://my.url/api.
I do have access to https://my.url/db/_utils, so I suppose CouchDB traffic is routed correctly. But this is only my assumption.

Here is an excerpt of my Traefik access log when creating a user and trying to log in:

> 10.0.0.133 - - [28/Apr/2023:14:49:04 +0000] "POST /api/registernewuser HTTP/2.0" 200 264 "-" "-" 304 "groceries-backend@docker" "http://10.0.20.9:8000" 15ms
> 10.0.0.133 - - [28/Apr/2023:14:49:18 +0000] "OPTIONS /api/issuetoken HTTP/2.0" 204 0 "-" "-" 305 "groceries-backend@docker" "http://10.0.20.9:8000" 17ms



Here is what I can see in the browser debugging session:

`{"loginSuccessful":true,"email":"kladderadeng@mydomainonetwo.com","fullname":"Kladderadeng","loginRoles":["crud"],"refreshJWT":"<token>","accessJWT":"<token","couchdbUrl":"https://groceries.mydomainonetwo.com/db","couchdbDatabase":"groceries"}`

And here an excerpt of the Docker container logs:

> groceries-backend     | STATUS: Registering New User:  kladderadeng
> groceries-couchdb     | [notice] 2023-04-28T14:48:50.245685Z nonode@nohost <0.791.0> 171a472baa groceries-couchdb:5984 10.0.20.9 couchdbadmin GET /_users/org.couchdb.user%3Akladderadeng 200 ok 1
> groceries-frontend    | 10.0.0.133 - - [28/Apr/2023:14:48:59 +0000] "GET /manifest.json HTTP/1.1" 200 438 "http://10.0.20.10/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58" "-"
> groceries-frontend    | 10.0.0.133 - - [28/Apr/2023:14:48:59 +0000] "GET /static/css/main.236bfcc5.css.map HTTP/1.1" 200 94205 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58" "-"
> groceries-frontend    | 10.0.0.133 - - [28/Apr/2023:14:48:59 +0000] "GET /static/js/5022.f54ea41b.chunk.js.map HTTP/1.1" 200 3884 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58" "-"
> groceries-frontend    | 10.0.0.133 - - [28/Apr/2023:14:48:59 +0000] "GET /static/js/9344.da98aeb8.chunk.js.map HTTP/1.1" 200 9185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58" "-"
> groceries-frontend    | 10.0.0.133 - - [28/Apr/2023:14:48:59 +0000] "GET /static/js/3315.2e61f13b.chunk.js.map HTTP/1.1" 200 11299 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58" "-"
> groceries-frontend    | 10.0.0.133 - - [28/Apr/2023:14:48:59 +0000] "GET /static/js/2849.7c577f81.chunk.js.map HTTP/1.1" 200 8088 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58" "-"
> groceries-frontend    | 10.0.0.133 - - [28/Apr/2023:14:49:00 +0000] "GET /static/js/main.aa6889a1.js.map HTTP/1.1" 200 7524245 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58" "-"
> groceries-couchdb     | [notice] 2023-04-28T14:49:01.911335Z nonode@nohost <0.1675.0> 77474818d8 localhost:5984 127.0.0.1 undefined GET / 200 ok 0
> groceries-backend     | STATUS: Registering New User:  kladderadeng
> groceries-couchdb     | [notice] 2023-04-28T14:49:04.384119Z nonode@nohost <0.791.0> 3e284ddde8 groceries-couchdb:5984 10.0.20.9 couchdbadmin GET /_users/org.couchdb.user%3Akladderadeng 200 ok 1
> groceries-backend     | STATUS: issuing token for device ID: "7839fe8f-154c-45e6-a6fd-2e10a710e858"
> groceries-couchdb     | [notice] 2023-04-28T14:49:18.210514Z nonode@nohost <0.1821.0> a0480c81fd groceries-couchdb:5984 10.0.20.9 kladderadeng GET /_session 200 ok 1
> groceries-couchdb     | [notice] 2023-04-28T14:49:18.213179Z nonode@nohost <0.791.0> 819185a065 groceries-couchdb:5984 10.0.20.9 couchdbadmin GET /_users/org.couchdb.user%3Akladderadeng 200 ok 1
> groceries-couchdb     | [notice] 2023-04-28T14:49:18.222146Z nonode@nohost <0.791.0> f8600eb46d groceries-couchdb:5984 10.0.20.9 couchdbadmin POST /_users 201 ok 7
> groceries-backend     | STATUS: issuing token for device ID: "7839fe8f-154c-45e6-a6fd-2e10a710e858"
> groceries-couchdb     | [notice] 2023-04-28T14:49:25.751300Z nonode@nohost <0.1899.0> 7b05846780 groceries-couchdb:5984 10.0.20.9 kladderadeng GET /_session 200 ok 1
> groceries-couchdb     | [notice] 2023-04-28T14:49:25.754107Z nonode@nohost <0.791.0> f0f1923e5e groceries-couchdb:5984 10.0.20.9 couchdbadmin GET /_users/org.couchdb.user%3Akladderadeng 200 ok 1
> groceries-couchdb     | [notice] 2023-04-28T14:49:25.762868Z nonode@nohost <0.791.0> 1642bbbf9e groceries-couchdb:5984 10.0.20.9 couchdbadmin POST /_users 201 ok 6
> groceries-couchdb     | [notice] 2023-04-28T14:49:32.015696Z nonode@nohost <0.1975.0> 72533bb830 localhost:5984 127.0.0.1 undefined GET / 200 ok 0


I do not see any "error" message that shows me that a part can not communicate with another. But of course I made a mistake somewhere. I do not want to make this post bigger by showing my docker-compose.yml or other config files, but whatever helps to understand what I did wrong I will post of course :-)

**Comment by davideshay** [comment]
Did the browser/javascript console show any errors at all - I see you tracked the network request which looks good. The console would normally show 3 status messages - 1 saying it is refreshing the token, 2 with the API server URL, and then a 3rd with the time in seconds until the JWT expires. After these, you should actually see some 404 errors as the pouchDB/couchDB starts replicating (these are "normal" as the message says). On the loaded page, the cloud icon should also a checkmark in it (on the header). If this is not a checkmark or has a slash through it, pouchDB replication has failed to start (which is the likely cause of not having the items loaded, etc.).  It is this pouchDB replication that goes from the frontend directly to couchDB.  There are other functions like logging in, sending friend requests, changing passwords, that go through the backendAPI which then talks to couchDB -- I believe you had all that correct.

So check there and let me know if there are any logs. I can see about adding some debug logging based on a switch or something too. I suppose your docker-compose.yml would help just to look at as well. Post wherever makes sense and send me a link.

**Comment by kladderadeng** [comment]
You were correct from the start, expecting that something with the HMAC setup is fishy!
I had a look at it again in a in-private session + debugging console and I could see a Bad HMAC message.

Why did I not see this in the last days when debugging? It seems the error only comes up once. In the Screenshot, the first 5 entries are from the very first attempt in a fresh in-private window. The following "issuetoken" entries where subsequent clicks on the Login button in the Frontend. So I made a mistake when debugging. I should have started with a fresh in-private session on every attempt.

![image](https://user-images.githubusercontent.com/111387593/235296254-6cc5408a-8b6c-4540-8f8f-61dcee56a872.png)

I will check the HMAC setup again today and I am pretty confident this will solve it. I will get back when I am done :-)

**Comment by kladderadeng** [comment]
It is embarassing, but I have to confess. It was the HMAC setup. For some reason, when copying or pasting the HMAC key into my docker-compose.yml I managed to cut off a single character at the end.
That´s it. That was the problem :-(

Thank you for your patience :-)
