### ISSUE TITLE
Maybe a Bug in "List Edit" regarding Categories

### ISSUE THREAD

**Issue by kladderadeng** [davideshay/groceries#23]
This happens in the Web UI 0.7.1. Maybe a bug, maybe a misunderstanding on my side.

1. Go to a list
2. Type in a new item in the Search field and press ENTER to create it. Fill out all mandatory fields and realize that you do not have a fitting category for the item yet.
3. Save the Item.
4. Go to Categories.
5. Create a new Category.
6. Go back to the List, open the Item and assign the Category, Save the Item.
7. Click on the Pen right of the List to edit the list.
8. The Category will be at the bottom of the list in deativated state.

Although the category is deactivated, the item stays in the list, so at least you do not miss it when you go shopping ;-)
But I would expect the category to be activated, since it is used by an active item in the current list.

Bonus:
After finishing my List in the Web UI, open the Android App on my Phone. The app flickers a bit while it synchronizes the current state and I see all my Items, but the categories are not in the same order as in the Web UI. Switch to another list and back to the list I just edited and the sorting is OK. I suppose the items + sort order are synchronized correctly, but the sort order is only applied once you open the list again?

**Comment by davideshay** [comment]
As for the initial issue, I have allowed for the creating of new units of measure and new categories directly from the Item creation/update screen so you don't have to do all those movements back and forth. Just hit the "+" button next to the UOM or Category drop-downs and a modal will open up allowing you to create a new one from there.

That being said, I don't currently have logic that when a category is added it becomes "active" on all lists. Even if the category is not "active" though, the item still shows up on the list if you have added it.  This would potentially only come into play if you had the setting "Add with same categories automatically".  In this case, let's say you created a category called "Organic Fruit", and maybe you had 2 different lists in a list group. At one of the stores, let's say they don't carry organic fruit. You could then uncheck that category at the store. In this case, if you added a new item "Organic Bananas" to the list, AND you had the setting to "Add with Same Categories automatically", it would add the organic bananas only to the 1 list and not the other.  All depends on how you shop/organize your lists.

I could certainly add some logic to automatically add any new categories to all available lists, just not sure that that is the common desired behavior either, and I am a bit loathe to continue to add new settings.  For instance, let's say you have two list groups - one for grocery stores and another for hardware stores. You might only have 5-6 categories at the hardware store that are relevant -- nuts/bolts, lawn supplies, etc. You might NOT want to add a new category "Organic Fruit" to that list automatically.

I'm also not seeing this behavior around sorting the lists or categories on Android differently, or needing a "refresh". Need to be able to replicate that in order to address.

**Comment by kladderadeng** [comment]
The topic Category creation and active / inactive is solved for me after your explanation. That all makes sense to me and I do not think it requires another logic. More so you only might create a new category here or there when you start fresh and once it is tailored to your needs you might never touch it again. Thanks for sharing your thoughts behind the design process, that cleared all up for me.

That sorting not happening instantly might also have been a hiccup in the sync / my network connection or some caching issue outside of your application. It all looks good today. I will keep an eye on it and if I think I can reproduce it, I will let you know how. Regarding the emulator / simulator, I do not have one (yet). We have 2 Android phones (Mi 9 Lite and Poco F1), both with Lineage, so if something else comes up I make sure I test with both devices first.
