### ISSUE TITLE
[Bug] Trying to check off item in List Group view breaks the list

### ISSUE THREAD

**Issue by Chifilly** [davideshay/groceries#53]
When trying to check off an item in the list group view, you get the warning pop up about "you probably want to do this in a list" (I don't understand the rationale behind that, but sure) so I want to `Continue/Ignore`. However, clicking either `Cancel` or `Continue/Ignore` makes the item unusable. `Cancel` shows the item as checked, and `Continue/Ignore` shows the item as unchecked, but both make the item completely uninteractable, and `Continue/Ignore` makes the entire list uninteractable. Reloading the page is needed to make it work again (refreshing causes a 404 so you have to manually go to the base domain which is a bit tedious, let me know if that should be opened as a separate issue), and going back to the list, nothing has changed.

There doesn't seem to be any errors in the logs for the backend, frontend, couchDB, or developer console, and looking at the network requests, it doesn't make any at all when clicking either button.

**Comment by davideshay** [comment]
Oddly enough I just encountered this bug as well. It is already fixed and will be a part of the upcoming 1.0.2 release.

As for why there is a warning, the thinking is that you might add items in list group mode, but you would likely want the list to be sorted by aisle/category when you are "shopping" / checking things off. You can't sort the items by category/aisle in list group mode because the category order is defined at the list level, not list group.  In any case, thanks for reporting, and this will be resolved this weekend.

**Comment by davideshay** [comment]
v1.0.2 now released with a fix for this. Let me know if that works.

**Comment by Chifilly** [comment]
Seems to work perfectly 👍🏽
