### ISSUE TITLE
How to provide environment variables to mobile app

### ISSUE THREAD

**Issue by LeoKlaus** [davideshay/groceries#7]
I'm trying to build the iOS app and can't manage to pass the default_api_url environment variable. I've created a file client/.env with `DEFAULT_API_URL=http://192.168.27.200:3333`

The console in XCode logs the following error:
`TypeError: undefined is not an object (evaluating 'window._env_.DEFAULT_API_URL')`

**Comment by davideshay** [comment]
I'll have to fire up xcode and see, but in the Android app, I have a file called env_config.js with this contents:
```
window._env_ = {
  DEFAULT_API_URL: "https://groceries.mydomain.com",
}
```

**Comment by davideshay** [comment]
Just release 0.5.1 -- it now works for me on the XCode Simulator using "ionic capacitor build ios".
If you want to update the default API URL, edit the file
./client/ios/App/App/public/env-config.js. You will have to edit the file AFTER you do the ionic capacitor build command, otherwise it will be reset.
